name: Build and push Docker image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t your_username/your_image_name:latest .
          echo "${{DOCKERHUB_PASSWORD}}" | docker login -u "${{DOCKERHUB_USERNAME}}" --password-stdin
          docker push your_username/your_image_name:latest